Feature: Using Citation Libraries
thegetty/quire pull request #332
Opened 2022-05-27 21:49 UTC by hbalenda

Adds a shortcode to demo using the `citation-style-lib` vs the current `citation` shortcode. 

The new shortcode accepts Quire `page` or `publication` data, translates it into CSL-JSON ([CSL Docs](https://docs.citationstyles.org/en/stable/specification.html), [CSL-JSON Schema](https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-citation.json)), and then uses [`simple-cite`](https://github.com/lewisacidic/simple-cite) and the Citation Style `style-chicago` and `style-mla` packages to generate a bibliography entry. 

`simple-cite` can also be used for [inline citations](https://github.com/lewisacidic/simple-cite#making-citations), which is worth investigating.

There are some slight differences between the formats, some of which (though likely not all) can be fixed with a closer reading of the citation schema. For example, I'm not sure if `book` is the correct `type` for a quire publication. 

Demo page is on `localhost:8080/citations`

2022-06-06 22:02 UTC, geealbers commented
@hbalenda, for the URL, in Hugo we started using `identifier.url` in publication,.yaml for the citations rather than `baseURL`, as we found there were many cases where baseURL wasn't set. Like for our netlify deploy.

2022-06-06 23:15 UTC, hbalenda commented
@geealbers Ah good to know - we are using `config.baseURL` extensively in the eleventy project, but it makes sense that a user shouldn't be required to edit anything there. We can replace those references on a separate branch.

Also thank you for the review last week. I've changed the style to Chicago fullnote bibliography, added italics, and documented how to configure the citation style and locale. The formatting still has a couple (very) slight differences, though I think the library version is actually correct and that they are things that were broken when moving the citation shortcode to eleventy.

2022-06-08 22:09 UTC, mphstudios approved these changes

2022-06-13 23:21 UTC, mphstudios commented on packages/11ty/_includes/components/citation/README.md
> +The citation component translates page data and data from `publication.yaml` into [CSL-JSON]((https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-citation.json)) and uses
```suggestion
The citation component translates page data and data from `publication.yaml` into [CSL-JSON]((https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-citation.json)) and uses the [Quire citation plugin](/blob/main/packages/11ty/_plugins/citations/README.md) to render that data in `MLA` or `Chicago` formats.
```

2022-06-13 23:26 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +To use, set the citation shortcode `type` to the style name.
```suggestion
To use, set the `citation` shortcode `type` to the style name.
```

2022-06-13 23:27 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +The Quire citations plugin uses [`simple-cite`]() and citation-styles [CSL-JSON](https://github.com/citation-style-language/schema#csl-json-schema) to generate citations with configurable locale and
inter-repository linking to the citation component woul
```suggestion
The Quire citations plugin uses [`simple-cite`](https://github.com/lewisacidic/simple-cite#readme) and citation-styles [CSL-JSON](https://github.com/citation-style-language/schema#csl-json-schema) to generate citations with configurable locale and style. It registers an eleventy javascript function `formatCitation`, which is used to create page and publication citations from the [`citations` component](https://github.com/thegetty/quire/packages/11ty/_includes/components/citation/).
```

2022-06-13 23:29 UTC, mphstudios requested changes
@hbalenda this is a really nice improvement to the use of standards and the flexibility of Quire.

2022-06-14 04:41 UTC, mphstudios approved these changes

2022-06-14 04:42 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +```
```suggestion
```sh
```

2022-06-14 04:43 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +```
```suggestion
```javascript
```

2022-06-14 04:43 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +```
```suggestion
```javascript
```

2022-06-14 04:43 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +```
```suggestion
```javascript
```

2022-06-14 04:43 UTC, mphstudios commented on packages/11ty/_plugins/citations/README.md
> +```npm install locale-fr-fr```
```suggestion
```sh
npm install locale-fr-fr
```
```

2022-06-14 04:44 UTC, mphstudios approved these changes

2022-06-14 16:50 UTC, merged