DEV-16148: Add support for `object_filters: false` to disable filtering and hide UI
thegetty/quire pull request #864
Opened 2023-10-11 21:46 UTC by anderspollack

2023-10-11 22:41 UTC, mphstudios commented on packages/11ty/_includes/components/object-filters/object-filters.webc
> +};
```suggestion
/**
 * When object_filters is set to `false` filters will not be rendered
 */
const getFilterOrder = ($data) => {
  return $data.object_filters !== false
    ? $data.object_filters || $data.objects.object_filters;
    : false;
  }
};
```

2023-10-11 22:55 UTC, mphstudios commented on packages/11ty/_includes/components/object-filters/objects-catalog.webc
> +      <div webc:if="!areFiltersDisabled($data)" class="object-filters__controls">
Using a positive assertion here may be easier to read
```suggestion
      <div webc:if="displayFilters($data)" class="object-filters__controls">
```

2023-10-11 22:56 UTC, mphstudios commented on packages/11ty/_includes/components/object-filters/objects-catalog.webc
> +}
```suggestion
const hasFilters = ($data) => {
  return $data.object_filters !== false || $data.objects.object_filters !== false;
}
```

2023-10-11 22:56 UTC, mphstudios requested changes
See inline comments.

2023-10-11 23:02 UTC, anderspollack commented
@mph changes in comments have been applied + tested

2023-10-12 00:46 UTC, mphstudios approved these changes

2023-10-12 01:09 UTC, merged