DEV-15887: Include title in epub manifest if no subtitle
thegetty/quire pull request #865
Opened 2023-10-11 22:39 UTC by anderspollack

2023-10-11 22:52 UTC, mphstudios commented on packages/11ty/_plugins/transforms/outputs/epub/manifest.js
> +    const joiner = title.endsWith('?') || title.endsWith('!') ? '' : ':';
More robustly, if the title does not end with punctuation, use a separator.
```suggestion
    const separator = title.match(/[.,:!?]$/ '' : ':';
```

2023-10-11 22:53 UTC, mphstudios commented on packages/11ty/_plugins/transforms/outputs/epub/manifest.js
> +      return title
```suggestion
      case subtitle && readingLine:
        return `${title}${separator} ${subtitle} ${readingLine}`
      case readingLine:
        return `${title} (${readingLine})`
      case subtitle:
        return `${title}${separator} ${subtitle}`
      default:
        return title
```

2023-10-11 22:54 UTC, mphstudios requested changes
We can proactively test for all punctuation when determining how to separate the `title` `subtitle` string.

2023-10-11 23:11 UTC, mphstudios commented on packages/11ty/_plugins/transforms/outputs/epub/manifest.js
> +    const joiner = title.endsWith('?') || title.endsWith('!') ? '' : ':';
An alternate functional approach
```
function endsWithPunctuation (string) {
  const punctuation = '.,:!?';
  return punctuation.some((character) => string.endsWith(character));
}
```

2023-10-11 23:45 UTC, anderspollack commented
@mphstudios changes applied + tested

2023-10-12 00:45 UTC, mphstudios approved these changes

2023-10-12 01:09 UTC, merged